"""
text_extractor.py

Production V1 - Colab Ready

Purpose
-------
Extract physical text objects from a PageRecord.

Input
-----
PageRecord from page_iterator.py

Output
------
PageRaw object containing:
- raw_text
- normalized_text
- text_blocks
- text_lines
- text_spans
- words
- fonts

This module only performs physical text extraction.
It does not perform:
- layout understanding
- reading order reconstruction
- heading detection
- table detection
- semantic analysis

Supported page types
--------------------
- PDF page:
    Uses PyMuPDF:
    - page.get_text("text")
    - page.get_text("dict")
    - page.get_text("words")

- Virtual TXT/DOCX page:
    Uses page_record.text_content

- Image page:
    Returns empty text. OCR will be handled later by OCR extractor.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple


try:
    import fitz  # PyMuPDF
except Exception:
    fitz = None


from document_ai.schemas.page_raw_schema import (
    PageRaw,
    TextBlockRaw,
    TextLineRaw,
    TextSpanRaw,
    WordRaw,
    FontRaw,
    make_id,
    normalize_bbox,
    merge_bboxes,
    normalize_pdf_text,
)


# ============================================================
# Config
# ============================================================

@dataclass
class TextExtractorConfig:
    """
    Configuration for TextExtractor.
    """

    extract_blocks: bool = True
    extract_lines: bool = True
    extract_spans: bool = True
    extract_words: bool = True
    extract_fonts: bool = True

    normalize_text: bool = True

    skip_empty_spans: bool = True
    skip_empty_lines: bool = True
    skip_empty_blocks: bool = True

    include_raw_pymupdf: bool = False


# ============================================================
# Text Extractor
# ============================================================

class TextExtractor:
    """
    Extract physical text objects from one page.

    This extractor converts PageRecord into PageRaw.
    PageRaw is the base input for:
    - ImageExtractor
    - DrawingExtractor
    - AnnotationExtractor
    - LinkExtractor
    - FontExtractor
    - PageExtractionPipeline
    """

    def __init__(self, config: Optional[TextExtractorConfig] = None):
        self.config = config or TextExtractorConfig()

    # --------------------------------------------------------
    # Public API
    # --------------------------------------------------------

    def process(self, page_record: Any) -> PageRaw:
        """
        Extract text from PageRecord.

        Parameters
        ----------
        page_record:
            PageRecord generated by PageIterator.

        Returns
        -------
        PageRaw
        """

        page_kind = getattr(page_record, "page_kind", "unknown")

        if page_kind == "pdf_page":
            return self._process_pdf_page(page_record)

        if page_kind in {"virtual_text_page", "virtual_docx_page"}:
            return self._process_virtual_text_page(page_record)

        if page_kind == "image_page":
            return self._empty_page_raw(
                page_record=page_record,
                warning="Image page has no text layer. OCR required.",
            )

        return self._empty_page_raw(
            page_record=page_record,
            warning=f"Unsupported page_kind for TextExtractor: {page_kind}",
        )

    # --------------------------------------------------------
    # PDF page
    # --------------------------------------------------------

    def _process_pdf_page(self, page_record: Any) -> PageRaw:
        page = getattr(page_record, "page_object", None)

        if page is None:
            return self._empty_page_raw(
                page_record=page_record,
                warning="PDF page_object is None.",
            )

        warnings: List[str] = []

        raw_text = ""
        normalized_text = ""

        text_blocks: List[TextBlockRaw] = []
        text_lines: List[TextLineRaw] = []
        text_spans: List[TextSpanRaw] = []
        words: List[WordRaw] = []
        fonts: List[FontRaw] = []

        # -----------------------------
        # 1. Extract raw page text
        # -----------------------------

        try:
            raw_text = page.get_text("text") or ""
            normalized_text = (
                normalize_pdf_text(raw_text)
                if self.config.normalize_text
                else raw_text
            )
        except Exception as exc:
            warnings.append(f"Failed to extract raw text: {exc}")

        # -----------------------------
        # 2. Extract blocks / lines / spans
        # -----------------------------

        text_dict: Dict[str, Any] = {}

        if (
            self.config.extract_blocks
            or self.config.extract_lines
            or self.config.extract_spans
        ):
            try:
                text_dict = page.get_text("dict") or {}
            except Exception as exc:
                warnings.append(f"Failed to extract text dict: {exc}")

        if text_dict:
            try:
                (
                    text_blocks,
                    text_lines,
                    text_spans,
                ) = self._extract_blocks_lines_spans(
                    text_dict=text_dict,
                    page_number=page_record.page_number,
                )
            except Exception as exc:
                warnings.append(f"Failed to parse text dict: {exc}")

        # -----------------------------
        # 3. Extract words
        # -----------------------------

        if self.config.extract_words:
            try:
                words = self._extract_words(
                    page=page,
                    page_number=page_record.page_number,
                )
            except Exception as exc:
                warnings.append(f"Failed to extract words: {exc}")

        # -----------------------------
        # 4. Extract font statistics
        # -----------------------------

        if self.config.extract_fonts:
            try:
                fonts = self._extract_fonts(
                    text_spans=text_spans,
                    page_number=page_record.page_number,
                )
            except Exception as exc:
                warnings.append(f"Failed to extract fonts: {exc}")

        metadata: Dict[str, Any] = {
            "extractor": "TextExtractor",
            "page_kind": page_record.page_kind,
            "raw_text_char_count": len(raw_text),
            "normalized_text_char_count": len(normalized_text),
            "text_block_count": len(text_blocks),
            "text_line_count": len(text_lines),
            "text_span_count": len(text_spans),
            "word_count": len(words),
            "font_count": len(fonts),
        }

        if self.config.include_raw_pymupdf:
            metadata["pymupdf_text_dict"] = text_dict

        return PageRaw(
            document_id=page_record.document_id,
            source_path=page_record.source_path,
            file_name=page_record.file_name,
            document_type=page_record.document_type,
            page_number=page_record.page_number,
            page_index=page_record.page_index,
            width=page_record.width,
            height=page_record.height,
            rotation=page_record.rotation,
            raw_text=raw_text,
            normalized_text=normalized_text,
            text_blocks=text_blocks,
            text_lines=text_lines,
            text_spans=text_spans,
            words=words,
            fonts=fonts,
            metadata=metadata,
            warnings=warnings,
        )

    def _extract_blocks_lines_spans(
        self,
        text_dict: Dict[str, Any],
        page_number: int,
    ) -> Tuple[List[TextBlockRaw], List[TextLineRaw], List[TextSpanRaw]]:
        """
        Parse PyMuPDF page.get_text("dict") output.
        """

        blocks_out: List[TextBlockRaw] = []
        lines_out: List[TextLineRaw] = []
        spans_out: List[TextSpanRaw] = []

        blocks = text_dict.get("blocks", []) or []

        for block_no, block in enumerate(blocks):
            # PyMuPDF block type:
            # 0 = text
            # 1 = image
            if block.get("type") != 0:
                continue

            raw_lines = block.get("lines", []) or []
            block_lines: List[TextLineRaw] = []

            for line_no, line in enumerate(raw_lines):
                raw_spans = line.get("spans", []) or []
                line_spans: List[TextSpanRaw] = []

                for span_no, span in enumerate(raw_spans):
                    text = span.get("text", "") or ""

                    if self.config.skip_empty_spans and not text.strip():
                        continue

                    normalized = (
                        normalize_pdf_text(text)
                        if self.config.normalize_text
                        else text
                    )

                    bbox = normalize_bbox(span.get("bbox"))

                    font = span.get("font")
                    size = self._safe_float(span.get("size"))
                    flags = span.get("flags")
                    color = span.get("color")

                    is_bold = self._is_bold_font(font=font, flags=flags)
                    is_italic = self._is_italic_font(font=font, flags=flags)

                    span_obj = TextSpanRaw(
                        span_id=make_id("span"),
                        page_number=page_number,
                        text=text,
                        normalized_text=normalized,
                        bbox=bbox,
                        font=font,
                        size=size,
                        flags=flags,
                        color=color,
                        block_no=block_no,
                        line_no=line_no,
                        span_no=span_no,
                        origin=self._normalize_origin(span.get("origin")),
                        ascender=self._safe_float(span.get("ascender")),
                        descender=self._safe_float(span.get("descender")),
                        is_bold=is_bold,
                        is_italic=is_italic,
                        is_upper=(
                            normalized.strip().isupper()
                            if normalized.strip()
                            else False
                        ),
                        metadata={
                            "raw_span": (
                                span
                                if self.config.include_raw_pymupdf
                                else None
                            )
                        },
                    )

                    line_spans.append(span_obj)
                    spans_out.append(span_obj)

                line_text = "".join(s.text for s in line_spans)
                line_normalized = "".join(s.normalized_text for s in line_spans)

                if self.config.skip_empty_lines and not line_normalized.strip():
                    continue

                line_bbox = normalize_bbox(line.get("bbox")) or merge_bboxes(
                    [s.bbox for s in line_spans]
                )

                line_obj = TextLineRaw(
                    line_id=make_id("line"),
                    page_number=page_number,
                    text=line_text,
                    normalized_text=line_normalized,
                    bbox=line_bbox,
                    block_no=block_no,
                    line_no=line_no,
                    spans=line_spans,
                    metadata={
                        "wmode": line.get("wmode"),
                        "dir": line.get("dir"),
                    },
                )

                block_lines.append(line_obj)
                lines_out.append(line_obj)

            block_text = "\n".join(l.text for l in block_lines)
            block_normalized = "\n".join(l.normalized_text for l in block_lines)

            if self.config.skip_empty_blocks and not block_normalized.strip():
                continue

            block_bbox = normalize_bbox(block.get("bbox")) or merge_bboxes(
                [l.bbox for l in block_lines]
            )

            block_obj = TextBlockRaw(
                block_id=make_id("block"),
                page_number=page_number,
                text=block_text,
                normalized_text=block_normalized,
                bbox=block_bbox,
                block_no=block_no,
                block_type="text",
                lines=block_lines,
                metadata={
                    "raw_block_no": block.get("number"),
                },
            )

            blocks_out.append(block_obj)

        return blocks_out, lines_out, spans_out

    def _extract_words(
        self,
        page: Any,
        page_number: int,
    ) -> List[WordRaw]:
        """
        Extract word-level objects from PyMuPDF.

        PyMuPDF word tuple format:
        (x0, y0, x1, y1, word, block_no, line_no, word_no)
        """

        words_out: List[WordRaw] = []

        raw_words = page.get_text("words") or []

        for item in raw_words:
            try:
                x0, y0, x1, y1, word, block_no, line_no, word_no = item[:8]

                text = str(word)
                normalized = (
                    normalize_pdf_text(text)
                    if self.config.normalize_text
                    else text
                )

                if not normalized.strip():
                    continue

                word_obj = WordRaw(
                    word_id=make_id("word"),
                    page_number=page_number,
                    text=text,
                    normalized_text=normalized,
                    bbox=[
                        float(x0),
                        float(y0),
                        float(x1),
                        float(y1),
                    ],
                    block_no=int(block_no),
                    line_no=int(line_no),
                    word_no=int(word_no),
                )

                words_out.append(word_obj)

            except Exception:
                continue

        return words_out

    def _extract_fonts(
        self,
        text_spans: List[TextSpanRaw],
        page_number: int,
    ) -> List[FontRaw]:
        """
        Build font statistics from text spans.
        """

        font_map: Dict[Tuple[str, Optional[float]], FontRaw] = {}

        for span in text_spans:
            if not span.font:
                continue

            key = (span.font, span.size)

            if key not in font_map:
                font_map[key] = FontRaw(
                    font_id=make_id("font"),
                    page_number=page_number,
                    font_name=span.font,
                    size=span.size,
                    count=1,
                    is_bold=span.is_bold,
                    is_italic=span.is_italic,
                )
            else:
                font_map[key].count += 1

        return list(font_map.values())

    # --------------------------------------------------------
    # Virtual TXT / DOCX page
    # --------------------------------------------------------

    def _process_virtual_text_page(self, page_record: Any) -> PageRaw:
        """
        Process TXT/DOCX virtual page.
        """

        raw_text = getattr(page_record, "text_content", "") or ""
        normalized_text = (
            normalize_pdf_text(raw_text)
            if self.config.normalize_text
            else raw_text
        )

        span = TextSpanRaw(
            span_id=make_id("span"),
            page_number=page_record.page_number,
            text=raw_text,
            normalized_text=normalized_text,
            bbox=None,
            font=None,
            size=None,
            block_no=0,
            line_no=0,
            span_no=0,
        )

        line = TextLineRaw(
            line_id=make_id("line"),
            page_number=page_record.page_number,
            text=raw_text,
            normalized_text=normalized_text,
            bbox=None,
            block_no=0,
            line_no=0,
            spans=[span],
        )

        block = TextBlockRaw(
            block_id=make_id("block"),
            page_number=page_record.page_number,
            text=raw_text,
            normalized_text=normalized_text,
            bbox=None,
            block_no=0,
            block_type="virtual_text",
            lines=[line],
        )

        return PageRaw(
            document_id=page_record.document_id,
            source_path=page_record.source_path,
            file_name=page_record.file_name,
            document_type=page_record.document_type,
            page_number=page_record.page_number,
            page_index=page_record.page_index,
            width=page_record.width,
            height=page_record.height,
            rotation=page_record.rotation,
            raw_text=raw_text,
            normalized_text=normalized_text,
            text_blocks=[block],
            text_lines=[line],
            text_spans=[span],
            words=[],
            fonts=[],
            metadata={
                "extractor": "TextExtractor",
                "page_kind": page_record.page_kind,
                "virtual_text_page": True,
                "raw_text_char_count": len(raw_text),
                "normalized_text_char_count": len(normalized_text),
            },
        )

    # --------------------------------------------------------
    # Empty PageRaw
    # --------------------------------------------------------

    def _empty_page_raw(
        self,
        page_record: Any,
        warning: Optional[str] = None,
    ) -> PageRaw:
        warnings = []

        if warning:
            warnings.append(warning)

        return PageRaw(
            document_id=page_record.document_id,
            source_path=page_record.source_path,
            file_name=page_record.file_name,
            document_type=page_record.document_type,
            page_number=page_record.page_number,
            page_index=page_record.page_index,
            width=page_record.width,
            height=page_record.height,
            rotation=page_record.rotation,
            raw_text="",
            normalized_text="",
            text_blocks=[],
            text_lines=[],
            text_spans=[],
            words=[],
            fonts=[],
            metadata={
                "extractor": "TextExtractor",
                "page_kind": getattr(page_record, "page_kind", "unknown"),
                "empty": True,
            },
            warnings=warnings,
        )

    # --------------------------------------------------------
    # Utility
    # --------------------------------------------------------

    def _safe_float(self, value: Any) -> Optional[float]:
        try:
            if value is None:
                return None
            return float(value)
        except Exception:
            return None

    def _normalize_origin(self, origin: Any) -> Optional[List[float]]:
        if origin is None:
            return None

        try:
            return [float(origin[0]), float(origin[1])]
        except Exception:
            return None

    def _is_bold_font(
        self,
        font: Optional[str],
        flags: Optional[int] = None,
    ) -> Optional[bool]:
        """
        Detect bold font.

        This is a heuristic.
        More precise font flag decoding can be added later.
        """

        if not font and flags is None:
            return None

        font_lower = font.lower() if font else ""

        if (
            "bold" in font_lower
            or "black" in font_lower
            or "heavy" in font_lower
            or "semibold" in font_lower
        ):
            return True

        return False

    def _is_italic_font(
        self,
        font: Optional[str],
        flags: Optional[int] = None,
    ) -> Optional[bool]:
        """
        Detect italic font.
        """

        if not font and flags is None:
            return None

        font_lower = font.lower() if font else ""

        if "italic" in font_lower or "oblique" in font_lower:
            return True

        return False
